version: '3'

services:

# ***** SPARK *****
  jupyter:
    container_name: jupyter
    image: jupyter/all-spark-notebook
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./jupyter/notebooks/:/home/jovyan/notebooks/
    labels: 
      kompose.service.type: loadbalancer

# ***** STREAMSETS *****
  streamsets:
    env_file:
    - ./env/.env.streamsets.dev
    volumes:
      - sdc-dev-data:/data
      - sdc-dev-stagelibs:/opt/streamsets-datacollector-3.5.1/streamsets-libs

# ***** ZOOKEEPER *****
  zookeeper:
    env_file:
    - ./env/.env.zookeeper.dev

# ***** KAFKA *****
  kafka-broker:
    env_file:
    - ./env/.env.kafkabroker.dev

# ***** KAFKA-REST *****
  kafka-rest:
    env_file:
    - ./env/.env.kafkarest.dev

# ***** ELASTICSEARCH *****
  elasticsearch:
    env_file:
    - ./env/.env.elasticsearch.dev
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

# ***** KIBANA *****
  kibana:
    env_file:
    - ./env/.env.kibana.dev
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

# ***** LOGSTASH *****
  logstash:
    env_file:
    - ./env/.env.streamsets.dev
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline

networks:
  kafkanet:

volumes:
  sdc-dev-stagelibs:
  sdc-dev-data: