version: '3'

services:

# ***** STREAMSETS *****
  streamsets:
    image: streamsets/datacollector:3.5.1
    ports:
      - 18630:18630
    environment:
      - KAFKA_BROKER=kafka-broker
    networks:
      - kafkanet
    depends_on:
      - zookeeper
      - kafka
      - kafka-rest
    labels:
      kompose.service.type: loadbalancer

# ***** ZOOKEEPER *****
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      - zk_id=1
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafkanet

# ***** KAFKA *****
  kafka-broker:
    build: ./kafka/
    image: bnoeson1.azurecr.io/finbot_kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms512M
    networks:
      - kafkanet

# ***** KAFKA-REST *****
  kafka-rest:
    image: confluentinc/cp-kafka-rest
    depends_on:
      - zookeeper
      - kafka
    environment:
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_REST_HOST_NAME=kafka-rest
      - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
      - KAFKA_REST_BOOTSTRAP_SERVERS=kafka-broker:9092
    networks:
      - kafkanet

# ***** ELASTICSEARCH *****
  elasticsearch:
    build: ./elasticsearch/
    image: bnoeson1.azurecr.io/finbot_elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - ELASTIC_PASSWORD=pwd
    networks:
      - kafkanet

# ***** KIBANA *****
  kibana:
    build: ./kibana/
    image: bnoeson1.azurecr.io/finbot_kibana
    ports:
      - 5601:5601
    networks:
      - kafkanet
    depends_on:
      - elasticsearch
      - kafka    
    labels: 
      kompose.service.type: loadbalancer

# ***** LOGSTASH *****
  logstash:
    build: ./logstash/
    image: bnoeson1.azurecr.io/finbot_logstash
    ports:
      - 5000:5000
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - kafkanet
    depends_on:
      - elasticsearch

networks:
  kafkanet:
