version: '3'

services:

# ***** STREAMSETS *****
  streamsets:
    container_name: streamsets
    image: streamsets/datacollector:3.5.1
    ports:
      - 18630:18630
    networks:
      - kafkanet
    depends_on:
      - zookeeper
      - kafka-broker
      - kafka-rest
    labels:
      kompose.service.type: loadbalancer

# ***** ZOOKEEPER *****
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    networks:
      - kafkanet

# ***** KAFKA *****
  kafka-broker:
    container_name: kafka-broker
    build: ./kafka/
    image: bnoeson/finbot_kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - kafkanet

# ***** KAFKA-REST *****
  kafka-rest:
    container_name: kafka-rest
    image: confluentinc/cp-kafka-rest
    depends_on:
      - zookeeper
      - kafka-broker
    networks:
      - kafkanet

# ***** ELASTICSEARCH *****
  elasticsearch:
    container_name: elasticsearch
    build: ./elasticsearch/
    image: bnoeson/finbot_elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - kafkanet

# ***** KIBANA *****
  kibana:
    container_name: kibana
    build: ./kibana/
    image: bnoeson/finbot_kibana
    ports:
      - 5601:5601
    networks:
      - kafkanet
    depends_on:
      - elasticsearch
      - kafka-broker
    labels: 
      kompose.service.type: loadbalancer

# ***** LOGSTASH *****
  logstash:
    container_name: logstash
    build: ./logstash/
    image: bnoeson/finbot_logstash
    ports:
      - 5000:5000
    networks:
      - kafkanet
    depends_on:
      - elasticsearch

networks:
  kafkanet:
