version: '3'

services:

# ***** SPARK *****
  jupyter:
    image: jupyter/all-spark-notebook
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./jupyter/notebooks/:/home/jovyan/notebooks/
    labels: 
      kompose.service.type: nodeport

# ***** STREAMSETS *****
  streamsets:
    environment:
      - APP_ENV=dev
      - KAFKA_BROKER=kafka-broker #
    volumes:
      - sdc-dev-data:/data
      - sdc-dev-stagelibs:/opt/streamsets-datacollector-3.5.1/streamsets-libs

# ***** ZOOKEEPER *****
  zookeeper:
    environment:
      - APP_ENV=dev
      - zk_id=1 #
      - ZOOKEEPER_CLIENT_PORT=2181 #

# ***** KAFKA *****
  kafka-broker:
    environment:
      - APP_ENV=dev
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 #
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092 #
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 #
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms512M #

# ***** KAFKA-REST *****
  kafka-rest:
    environment:
      - APP_ENV=dev
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181 #
      - KAFKA_REST_HOST_NAME=kafka-rest #
      - KAFKA_REST_LISTENERS=http://0.0.0.0:8082 #
      - KAFKA_REST_BOOTSTRAP_SERVERS=kafka-broker:9092 #

# ***** ELASTICSEARCH *****
  elasticsearch:
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - ELASTIC_PASSWORD=pwd
      - APP_ENV=dev
      - ES_JAVA_OPTS=-Xmx256m -Xms256m #

# ***** KIBANA *****
  kibana:
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - APP_ENV=dev

# ***** LOGSTASH *****
  logstash:
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - APP_ENV=dev
      - LS_JAVA_OPTS=-Xmx256m -Xms256m #

networks:
  kafkanet:

volumes:
  sdc-dev-stagelibs:
  sdc-dev-data: