version: '3'

services:

# ***** STREAMSETS *****
  streamsets:
    env_file:
    - ./env/.env.streamsets.prod
    volumes:
      - sdc-data:/data
      - sdc-stagelibs:/opt/streamsets-datacollector-3.5.1/streamsets-libs

# ***** ZOOKEEPER *****
  zookeeper:
    env_file:
    - ./env/.env.zookeeper.prod

# ***** KAFKA *****
  kafka-broker:
    env_file:
    - ./env/.env.kafkabroker.prod

# ***** KAFKA-REST *****
  kafka-rest:
    env_file:
    - ./env/.env.kafkarest.prod

# ***** ELASTICSEARCH *****
  elasticsearch:
    env_file:
    - ./env/.env.elasticsearch.prod

# ***** KIBANA *****
  kibana:
    env_file:
    - ./env/.env.kibana.prod

# ***** LOGSTASH *****
  logstash:
    env_file:
    - ./env/.env.logstash.prod

volumes:
  sdc-stagelibs:
  sdc-data: