apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert -f docker-compose.yml
      -f docker-compose.override.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-rest
  name: kafka-rest
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-rest
    spec:
      containers:
      - env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: APP_ENV
              name: kafka-rest-env--env-kafkarest-dev
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: KAFKA_REST_BOOTSTRAP_SERVERS
              name: kafka-rest-env--env-kafkarest-dev
        - name: KAFKA_REST_HOST_NAME
          valueFrom:
            configMapKeyRef:
              key: KAFKA_REST_HOST_NAME
              name: kafka-rest-env--env-kafkarest-dev
        - name: KAFKA_REST_LISTENERS
          valueFrom:
            configMapKeyRef:
              key: KAFKA_REST_LISTENERS
              name: kafka-rest-env--env-kafkarest-dev
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              key: KAFKA_REST_ZOOKEEPER_CONNECT
              name: kafka-rest-env--env-kafkarest-dev
        image: confluentinc/cp-kafka-rest
        name: kafka-rest
        resources: {}
      restartPolicy: Always
status: {}
