apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe -f docker-compose.yml -f docker-compose.prod.yml
      convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: streamsets
  name: streamsets
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: streamsets
    spec:
      containers:
      - env:
        - name: APP_ENV
          value: prod
        image: streamsets/datacollector:3.5.1
        name: streamsets
        ports:
        - containerPort: 18630
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: sdc-data
        - mountPath: /opt/streamsets-datacollector-3.5.1/streamsets-libs
          name: sdc-stagelibs
      restartPolicy: Always
      volumes:
      - name: sdc-data
        persistentVolumeClaim:
          claimName: sdc-data
      - name: sdc-stagelibs
        persistentVolumeClaim:
          claimName: sdc-stagelibs
status: {}
