#--- # https://kubernetes.io/docs/concepts/storage/storage-classes/
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: azuredisk
#provisioner: kubernetes.io/azure-disk
#parameters:
#  skuname: Standard_LRS
#  kind: Shared
#  mountOptions: "dir_mode=0777,file_mode=0777"
#---
apiVersion: v1
kind: Service
metadata:
  name: datacollector
  labels:
    app: datacollector
spec:
  ports:
  - port: 18630
    targetPort: 18630
    name: ui
  selector:
    app: datacollector
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: datacollector
spec:
  serviceName: "datacollector"
  replicas: 1
  template:
    metadata:
      labels:
        app: datacollector
    spec:
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 10
      containers:
      - name: datacollector
        image: streamsets/datacollector:3.5.1
        ports:
        - containerPort: 18630
          name: ui
        readinessProbe:
          exec:
            command: ["curl", "127.0.0.1:18630/public-rest/ping"]
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data
        - name: data
          mountPath: /opt/streamsets-datacollector-3.5.1/streamsets-libs/
          subPath: stagelibs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 100Mi