apiVersion: v1
data:
  APP_ENV: dev
  ZOOKEEPER_CLIENT_PORT: "2181"
  zk_id: "1"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper-env--env-zookeeper-dev
  name: zookeeper-env--env-zookeeper-dev
